### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by Nisseiparken** [whosliam/ETNCRAFT#2]
The program does not start when I click on the exe file. Also as admin. Version 2.2 and 2.3 worked for a while but they are not running now either. I tried 2.4 now but it's the same. I have the last win 10 pro 1709.

**Comment by cmadison0005** [comment]
Is the exe in the root directory of the downloaded folder? Or was it copied out to your desktop?

**Comment by Nisseiparken** [comment]
c:\ETNCRAFT_V2.0.4

**Comment by Nisseiparken** [comment]
now i try the program in one of my mining rigs but it does not start there either

**Comment by whosliam** [comment]
Maybe anti virus related? If it worked then just stopped. That is my guess.
No errors being displayed?

**Comment by Nisseiparken** [comment]
[https://imgur.com/a/82vUb](url)

**Comment by Nisseiparken** [comment]
https://imgur.com/a/82vUb

**Comment by whosliam** [comment]
was their any resolution to this?

**Comment by Nisseiparken** [comment]
I have had the program excluded in the Eset from day 1 so it's not the virus program that causes the error. Unless parts of the program are installed under Roaming or Local. In that case, that part of the program is not excluded from Eset.

**Comment by whosliam** [comment]
Are you able to run just the miner without the GUI?
Try running ETNCRAFT-XMR.exe within the app_assets folder.

**Comment by Nisseiparken** [comment]
Yes I can. 
I have no trouble usingAwesome Miner or both NiceHash miners. I can also use Sumo Easy miner and Winminer without any problems
